productName = "electron-esm-template"

appId = "com.electron.demo.mac"

copyright = "Copyright © 2023-2032 GuangZhou electron-esm-template"

files = ["src/**/*"]

asar = false

[electronDownload]
platform = "darwin"
arch = "x64"
cache = ".yarn"

[directories]
output = ".build"
